//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incentivapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Premio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Premio()
        {
            this.Medicions = new HashSet<Medicion>();
        }
    
        public int idPremio { get; set; }
        [Required(ErrorMessage = "El campo valor es requerido")]
        public string valor { get; set; }
        [Required(ErrorMessage ="El campo nombre es requerido")]
        public string nombre { get; set; }
        [Required(ErrorMessage ="El campo tipo de premio es requerido")]
        public Nullable<int> idTipoPremio { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual TipoPremio TipoPremio { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicion> Medicions { get; set; }
    }
}
