//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incentivapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Propietaria2Context : DbContext
    {
        public Propietaria2Context()
            : base("name=Propietaria2Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Premio> Premios { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TipoPremio> TipoPremios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Medicion> Medicions { get; set; }
        public virtual DbSet<Rango> Rangoes { get; set; }
    }
}
