//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incentivapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rango
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rango()
        {
            this.Medicions = new HashSet<Medicion>();
        }
    
        public int idRango { get; set; }
        [Required(ErrorMessage = "Debe Proporcionar un valor de inicio")]
        public string Inicio { get; set; }
        [Required(ErrorMessage = "Debe Proporcionar un valor de Fin")]
        public string Fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicion> Medicions { get; set; }
    }
}
